# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？
    #布尔值\浮点型\整数型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [2]:
sum((sum(range(1, 100)[::2]), -sum(range(1, 100)[1::2])))

50

1.3  将字符串 s="yoyo" 转换成列表

In [26]:
 s = "yoyo"
list(s)

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        # 理解这段代码，并说出它是如何取数的
        # 利用range函数生成1-100的数，取3的倍数，取最后十个数

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [27]:
class dif:
    def __init__(self,dif, a, b):
        self.dif=dif
        self.a = a
        self.b = b
    def pdif(self):
        return {self.dif+'_dif': (self.a-self.b)}

one = dif('one',15, 7)
print(one.pdif())

two = dif('two', 66, 20)
print(two.pdif())

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [21]:
import numpy as np
import pandas as pd
data=pd.read_excel('/Users/janicewoll/Desktop/sz50.xlsx',sheet_name='600029.XSHG', index_col='datetime')
data_frame= pd.DataFrame(data)
data_frame = data['close']
data_frame.values

array([11.64, 11.72, 11.8 , 11.8 , 11.85, 12.73, 12.13, 11.98, 11.97,
       12.02, 11.97, 12.03, 11.98, 12.03, 12.17, 12.18, 12.22, 12.08,
       12.03, 11.89, 11.89, 11.95, 11.98, 12.15, 12.2 , 12.18, 12.3 ,
       12.48, 12.3 , 12.68, 12.76, 12.79, 12.61, 13.07, 12.69, 12.71,
       12.86, 12.76, 12.74, 12.88, 12.78, 12.73, 12.69, 12.76, 12.83,
       12.91, 13.09, 13.16, 12.96, 12.81, 12.79, 13.01, 13.09, 13.52,
       13.54, 13.32, 13.47, 13.49, 13.62, 13.77, 13.95, 13.67, 13.63,
       13.45, 13.49, 13.39, 13.27, 13.32, 13.44, 13.32, 13.01, 12.61,
       12.78, 12.71, 12.84, 12.96, 12.86, 13.06, 13.21, 13.19, 13.06,
       13.29, 13.5 , 13.49, 13.52, 13.35, 13.35, 13.21, 13.35, 13.5 ,
       13.52, 13.73, 14.03, 14.25, 14.53, 14.31, 14.38, 14.46, 14.38,
       14.76, 14.89, 14.99, 14.82, 14.59, 14.67, 14.67, 14.99, 14.74,
       14.76, 14.82, 14.63, 14.94, 14.53, 14.25, 14.3 , 14.36, 14.21,
       14.2 , 14.28, 14.26, 14.16, 13.82, 13.83, 13.7 , 13.9 , 14.11,
       14.1 , 14.18,

In [22]:
import talib as ta
MA = ta.MA(data_frame.values,10)
print(type(MA))
print(MA[-5:])

<class 'numpy.ndarray'>
[15.145 15.239 15.353 15.528 15.736]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [24]:
from datetime import datetime
import pandas as pd
symbol=['600029.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data =  pd.read_excel('/Users/janicewoll/Desktop/sz50.xlsx',sheet_name=s, index_col='datetime')
    data_dict[s] = data.loc['2017-03-21':'2017-05-10']
PN = pd.Panel(data_dict)
print(PN)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 34 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-03-21 15:00:00 to 2017-05-10 15:00:00
Minor_axis axis: close to volume


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [33]:
import numpy as np
a=np.array(PN)
print(a.shape)
s_close=a[:,-20:,0]
print(s_close)

(3, 34, 5)
[[13.67 13.63 13.45 13.49 13.39 13.27 13.32 13.44 13.32 13.01 12.61 12.78
  12.71 12.84 12.96 12.86 13.06 13.21 13.19 13.06]
 [  nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan   nan
    nan   nan   nan   nan   nan   nan   nan   nan]
 [80.63 80.43 80.38 80.67 79.96 79.51 80.18 80.79 81.01 81.66 84.01 84.71
  85.   84.93 85.11 84.68 83.41 84.59 85.11 89.36]]


3.5 建立一个5*5的矩阵，值从0到24

In [34]:
Z = np.arange(0, 25).reshape(5, 5)
print(Z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
